/etc/nwa50be-setup-complete
/etc/nwa50be-management-cidr
/etc/dropbear/authorized_keys
/etc/shadow
/etc/config/dropbear
/etc/config/firewall
/etc/config/network
/etc/config/uhttpd
/etc/config/wireless
